name: jenkins-infra
services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/viralforge:/home/ubuntu/viralforge
      - /home/ubuntu/ettametta:/home/ubuntu/ettametta
    user: "root" # Required to access docker.sock for building images inside pipeline
