name: Ettametta Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to OCI ARM Server
      uses: appleboy/ssh-action@master
      with:
        host: \${{ secrets.OCI_HOST }}
        username: ubuntu
        key: \${{ secrets.OCI_PRIVATE_KEY }}
        script: |
          cd ~/viral_forge
          git pull origin main
          docker-compose up -d --build
